### ISSUE TITLE
Error when running watch

### ISSUE THREAD

**Issue by JanMisker** [burhanuday/react-library-parcel#1]
I get this error when running `npm run watch`, any idea how to resolve it?

```
> react-library@1.0.0 watch
> parcel watch

🚨 Build failed.

@parcel/core: Failed to resolve '@parcel/transformer-react-refresh-wrap/lib/helpers/helpers.js' from
'./react-library-parcel/node_modules/@parcel/transformer-react-refresh-wrap/lib/ReactRefreshWrapTransformer.js'

@parcel/resolver-default: External dependency "@parcel/transformer-react-refresh-wrap" is not declared in
package.json.

  /Users/janmisker/Developer/react-library-parcel/package.json:1:1
  > 1 | {
  >   | ^
    2 |   "name": "react-library",
    3 |   "version": "1.0.0",

  💡 Add "@parcel/transformer-react-refresh-wrap" as a dependency.

```

**Comment by burhanuday** [comment]
Can you delete node_modules and the package-lock file.

Then install again with yarn instead?

Might be a dependencies related issue

**Comment by JanMisker** [comment]
Same problem, don't you get the same error?

**Comment by burhanuday** [comment]
Try changing ` "watch": "parcel watch"` to just ` "watch": "parcel"` in `package.json`. Parcel does not seem to check devDependencies. I'll fix this repo in a bit

**Comment by burhanuday** [comment]
Able to reproduce it. Need some time to figure this out. In the meantime, i suggest replacing `parcel watch` with `parcel`

**Comment by burhanuday** [comment]
I am using the same config with my OSS library here - https://github.com/burhanuday/react-transliterate/blob/master/package.json. Confused so as to why i didnt get this error there

**Comment by JanMisker** [comment]
Maybe talk further in the issue in https://github.com/parcel-bundler/parcel/issues/6955
